apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blis-pvc
  namespace: blis
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  storageClass: ocs-storagecluster-cephfs   # <---- edit this for your cluster
