name: simulator_testing_for_scenario_1
description: Handcrafted test data for model
vllm:
      gpu_memory_utilization: 0.9
      block_size: 16
      max_model_len: 2048
      max_num_batched_tokens: 2048
      max_num_seqs: 1
      long_prefill_token_threshold: 2048
      seed: 42
      gpu_type: NVIDIA-H100-80GB-HBM3
      gpu_memory_min: 50000
data:
    workload:
      input_lens: [20, 40, 80, 120, 160, 240, 320, 400, 550, 640, 800, 950, 1050, 1200, 1350, 1400, 1600]
      num_exps: 10
client:
    temperature: 0.0
    output_len: 1
    seed: 42