client_template:
  output_len: 1
  seed: 42
  temperature: 0.0
description: Handcrafted test data for model
experiments:
- chunk_size: 256
  data:
    workloads:
    - deltas:
      - 188
      - 953
      - 4831
    - deltas:
      - 3714
      - 96
      - 1228
    - deltas:
      - 6609
      - 408
      - 717
    - deltas:
      - 81
      - 1429
      - 5155
  name: benchmark-1
  vllm:
    block_size: 16
    gpu_memory_min: 50000
    gpu_memory_utilization: 0.9
    gpu_type: NVIDIA-H100-80GB-HBM3
    long_prefill_token_threshold: 256
    max_model_len: 8192
    max_num_batched_tokens: 2048
    max_num_seqs: 1
    seed: 42
- chunk_size: 512
  data:
    workloads:
    - deltas:
      - 4286
      - 239
      - 817
    - deltas:
      - 939
      - 3875
      - 1482
    - deltas:
      - 801
      - 1438
      - 2256
    - deltas:
      - 2615
      - 2417
      - 3072
  name: benchmark-2
  vllm:
    block_size: 16
    gpu_memory_min: 50000
    gpu_memory_utilization: 0.9
    gpu_type: NVIDIA-H100-80GB-HBM3
    long_prefill_token_threshold: 512
    max_model_len: 8192
    max_num_batched_tokens: 2048
    max_num_seqs: 1
    seed: 42
- chunk_size: 1024
  data:
    workloads:
    - deltas:
      - 338
      - 5139
      - 286
    - deltas:
      - 12
      - 2330
      - 2687
    - deltas:
      - 1781
      - 3126
      - 603
    - deltas:
      - 1844
      - 2290
      - 459
  name: benchmark-3
  vllm:
    block_size: 16
    gpu_memory_min: 50000
    gpu_memory_utilization: 0.9
    gpu_type: NVIDIA-H100-80GB-HBM3
    long_prefill_token_threshold: 1024
    max_model_len: 8192
    max_num_batched_tokens: 2048
    max_num_seqs: 1
    seed: 42
- chunk_size: 2048
  data:
    workloads:
    - deltas:
      - 3844
      - 2536
      - 1405
    - deltas:
      - 408
      - 3577
      - 1217
    - deltas:
      - 747
      - 602
      - 3006
    - deltas:
      - 3689
      - 204
      - 3218
  name: benchmark-4
  vllm:
    block_size: 16
    gpu_memory_min: 50000
    gpu_memory_utilization: 0.9
    gpu_type: NVIDIA-H100-80GB-HBM3
    long_prefill_token_threshold: 2048
    max_model_len: 8192
    max_num_batched_tokens: 2048
    max_num_seqs: 1
    seed: 42
- chunk_size: 4096
  data:
    workloads:
    - deltas:
      - 116
      - 3168
      - 1539
    - deltas:
      - 698
      - 4364
      - 2018
    - deltas:
      - 3114
      - 162
      - 2087
    - deltas:
      - 1966
      - 1697
      - 962
  name: benchmark-5
  vllm:
    block_size: 16
    gpu_memory_min: 50000
    gpu_memory_utilization: 0.9
    gpu_type: NVIDIA-H100-80GB-HBM3
    long_prefill_token_threshold: 4096
    max_model_len: 8192
    max_num_batched_tokens: 2048
    max_num_seqs: 1
    seed: 42
name: simulator_testing_for_scenario_3
warmstart:
  prompt_count: 50
  prompt_len: 128
