client_template:
  output_len: 1
  seed: 42
  temperature: 0.0
description: Handcrafted train data for model
experiments:
- chunk_size: 256
  data:
    workloads:
    - deltas:
      - 2278
      - 2647
      - 1801
    - deltas:
      - 643
      - 6772
      - 609
  name: benchmark-1
  vllm:
    block_size: 16
    gpu_memory_min: 50000
    gpu_memory_utilization: 0.9
    gpu_type: NVIDIA-H100-80GB-HBM3
    long_prefill_token_threshold: 256
    max_model_len: 8192
    max_num_batched_tokens: 2048
    max_num_seqs: 1
    seed: 42
- chunk_size: 512
  data:
    workloads:
    - deltas:
      - 439
      - 3931
      - 544
    - deltas:
      - 171
      - 1755
      - 2173
  name: benchmark-2
  vllm:
    block_size: 16
    gpu_memory_min: 50000
    gpu_memory_utilization: 0.9
    gpu_type: NVIDIA-H100-80GB-HBM3
    long_prefill_token_threshold: 512
    max_model_len: 8192
    max_num_batched_tokens: 2048
    max_num_seqs: 1
    seed: 42
- chunk_size: 1024
  data:
    workloads:
    - deltas:
      - 770
      - 4149
      - 2151
    - deltas:
      - 1210
      - 4789
      - 361
  name: benchmark-3
  vllm:
    block_size: 16
    gpu_memory_min: 50000
    gpu_memory_utilization: 0.9
    gpu_type: NVIDIA-H100-80GB-HBM3
    long_prefill_token_threshold: 1024
    max_model_len: 8192
    max_num_batched_tokens: 2048
    max_num_seqs: 1
    seed: 42
- chunk_size: 2048
  data:
    workloads:
    - deltas:
      - 2347
      - 939
      - 2300
    - deltas:
      - 4644
      - 754
      - 16
  name: benchmark-4
  vllm:
    block_size: 16
    gpu_memory_min: 50000
    gpu_memory_utilization: 0.9
    gpu_type: NVIDIA-H100-80GB-HBM3
    long_prefill_token_threshold: 2048
    max_model_len: 8192
    max_num_batched_tokens: 2048
    max_num_seqs: 1
    seed: 42
- chunk_size: 4096
  data:
    workloads:
    - deltas:
      - 728
      - 3784
      - 815
    - deltas:
      - 4961
      - 28
      - 205
  name: benchmark-5
  vllm:
    block_size: 16
    gpu_memory_min: 50000
    gpu_memory_utilization: 0.9
    gpu_type: NVIDIA-H100-80GB-HBM3
    long_prefill_token_threshold: 4096
    max_model_len: 8192
    max_num_batched_tokens: 2048
    max_num_seqs: 1
    seed: 42
name: simulator_training_for_scenario_3
warmstart:
  prompt_count: 50
  prompt_len: 128
