client_template:
  output_len: 1
  seed: 42
  temperature: 0.0
description: Handcrafted train data for model
experiments:
- chunk_size: 256
  data:
    workloads:
    - deltas:
      - 3292
      - 3199
      - 289
    - deltas:
      - 475
      - 1020
      - 2873
    - deltas:
      - 1703
      - 1651
      - 1347
    - deltas:
      - 2791
      - 1080
      - 874
  name: benchmark-1
  vllm:
    block_size: 16
    gpu_memory_min: 50000
    gpu_memory_utilization: 0.9
    gpu_type: NVIDIA-H100-80GB-HBM3
    long_prefill_token_threshold: 256
    max_model_len: 8192
    max_num_batched_tokens: 2048
    max_num_seqs: 1
    seed: 42
- chunk_size: 512
  data:
    workloads:
    - deltas:
      - 3174
      - 1520
      - 925
    - deltas:
      - 1501
      - 1806
      - 3417
    - deltas:
      - 2836
      - 2182
      - 1166
    - deltas:
      - 1346
      - 2795
      - 2980
  name: benchmark-2
  vllm:
    block_size: 16
    gpu_memory_min: 50000
    gpu_memory_utilization: 0.9
    gpu_type: NVIDIA-H100-80GB-HBM3
    long_prefill_token_threshold: 512
    max_model_len: 8192
    max_num_batched_tokens: 2048
    max_num_seqs: 1
    seed: 42
- chunk_size: 1024
  data:
    workloads:
    - deltas:
      - 4566
      - 1067
      - 1982
    - deltas:
      - 4772
      - 420
      - 1234
    - deltas:
      - 261
      - 1560
      - 4700
    - deltas:
      - 1122
      - 2040
      - 1155
  name: benchmark-3
  vllm:
    block_size: 16
    gpu_memory_min: 50000
    gpu_memory_utilization: 0.9
    gpu_type: NVIDIA-H100-80GB-HBM3
    long_prefill_token_threshold: 1024
    max_model_len: 8192
    max_num_batched_tokens: 2048
    max_num_seqs: 1
    seed: 42
- chunk_size: 2048
  data:
    workloads:
    - deltas:
      - 992
      - 1473
      - 2279
    - deltas:
      - 3997
      - 741
      - 454
    - deltas:
      - 3034
      - 1629
      - 185
    - deltas:
      - 3845
      - 500
      - 1467
  name: benchmark-4
  vllm:
    block_size: 16
    gpu_memory_min: 50000
    gpu_memory_utilization: 0.9
    gpu_type: NVIDIA-H100-80GB-HBM3
    long_prefill_token_threshold: 2048
    max_model_len: 8192
    max_num_batched_tokens: 2048
    max_num_seqs: 1
    seed: 42
- chunk_size: 4096
  data:
    workloads:
    - deltas:
      - 2694
      - 457
      - 1330
    - deltas:
      - 1385
      - 3377
      - 3038
    - deltas:
      - 4224
      - 1406
      - 8
    - deltas:
      - 673
      - 3500
      - 1762
  name: benchmark-5
  vllm:
    block_size: 16
    gpu_memory_min: 50000
    gpu_memory_utilization: 0.9
    gpu_type: NVIDIA-H100-80GB-HBM3
    long_prefill_token_threshold: 4096
    max_model_len: 8192
    max_num_batched_tokens: 2048
    max_num_seqs: 1
    seed: 42
name: simulator_training_for_scenario_3
warmstart:
  prompt_count: 50
  prompt_len: 128
