client_template:
  output_len: 1
  seed: 42
  temperature: 0.0
description: Handcrafted train data for model
experiments:
- chunk_size: 256
  data:
    workloads:
    - deltas:
      - 1007
      - 2645
      - 3732
    - deltas:
      - 633
      - 6
      - 5921
  name: benchmark-1
  vllm:
    block_size: 16
    gpu_memory_min: 50000
    gpu_memory_utilization: 0.9
    gpu_type: NVIDIA-H100-80GB-HBM3
    long_prefill_token_threshold: 256
    max_model_len: 8192
    max_num_batched_tokens: 2048
    max_num_seqs: 1
    seed: 42
- chunk_size: 512
  data:
    workloads:
    - deltas:
      - 110
      - 1073
      - 6329
    - deltas:
      - 806
      - 4360
      - 689
  name: benchmark-2
  vllm:
    block_size: 16
    gpu_memory_min: 50000
    gpu_memory_utilization: 0.9
    gpu_type: NVIDIA-H100-80GB-HBM3
    long_prefill_token_threshold: 512
    max_model_len: 8192
    max_num_batched_tokens: 2048
    max_num_seqs: 1
    seed: 42
- chunk_size: 1024
  data:
    workloads:
    - deltas:
      - 208
      - 3469
      - 825
    - deltas:
      - 3330
      - 38
      - 864
  name: benchmark-3
  vllm:
    block_size: 16
    gpu_memory_min: 50000
    gpu_memory_utilization: 0.9
    gpu_type: NVIDIA-H100-80GB-HBM3
    long_prefill_token_threshold: 1024
    max_model_len: 8192
    max_num_batched_tokens: 2048
    max_num_seqs: 1
    seed: 42
- chunk_size: 2048
  data:
    workloads:
    - deltas:
      - 1761
      - 1519
      - 1714
    - deltas:
      - 19
      - 1043
      - 4824
  name: benchmark-4
  vllm:
    block_size: 16
    gpu_memory_min: 50000
    gpu_memory_utilization: 0.9
    gpu_type: NVIDIA-H100-80GB-HBM3
    long_prefill_token_threshold: 2048
    max_model_len: 8192
    max_num_batched_tokens: 2048
    max_num_seqs: 1
    seed: 42
- chunk_size: 4096
  data:
    workloads:
    - deltas:
      - 4605
      - 1957
      - 582
    - deltas:
      - 70
      - 2595
      - 2050
  name: benchmark-5
  vllm:
    block_size: 16
    gpu_memory_min: 50000
    gpu_memory_utilization: 0.9
    gpu_type: NVIDIA-H100-80GB-HBM3
    long_prefill_token_threshold: 4096
    max_model_len: 8192
    max_num_batched_tokens: 2048
    max_num_seqs: 1
    seed: 42
name: simulator_training_for_scenario_3
warmstart:
  prompt_count: 50
  prompt_len: 128
