client_template:
  output_len: 1
  seed: 42
  temperature: 0.0
description: Handcrafted test data for model
experiments:
- chunk_size: 256
  data:
    workloads:
    - deltas:
      - 21
      - 4879
      - 15
    - deltas:
      - 3681
      - 2195
      - 2088
  name: benchmark-1
  vllm:
    block_size: 16
    gpu_memory_min: 50000
    gpu_memory_utilization: 0.9
    gpu_type: NVIDIA-H100-80GB-HBM3
    long_prefill_token_threshold: 256
    max_model_len: 8192
    max_num_batched_tokens: 2048
    max_num_seqs: 1
    seed: 42
- chunk_size: 512
  data:
    workloads:
    - deltas:
      - 3052
      - 886
      - 1687
    - deltas:
      - 2140
      - 1327
      - 1700
  name: benchmark-2
  vllm:
    block_size: 16
    gpu_memory_min: 50000
    gpu_memory_utilization: 0.9
    gpu_type: NVIDIA-H100-80GB-HBM3
    long_prefill_token_threshold: 512
    max_model_len: 8192
    max_num_batched_tokens: 2048
    max_num_seqs: 1
    seed: 42
- chunk_size: 1024
  data:
    workloads:
    - deltas:
      - 3984
      - 1288
      - 475
    - deltas:
      - 3306
      - 210
      - 705
  name: benchmark-3
  vllm:
    block_size: 16
    gpu_memory_min: 50000
    gpu_memory_utilization: 0.9
    gpu_type: NVIDIA-H100-80GB-HBM3
    long_prefill_token_threshold: 1024
    max_model_len: 8192
    max_num_batched_tokens: 2048
    max_num_seqs: 1
    seed: 42
- chunk_size: 2048
  data:
    workloads:
    - deltas:
      - 588
      - 3401
      - 341
    - deltas:
      - 67
      - 3959
      - 1592
  name: benchmark-4
  vllm:
    block_size: 16
    gpu_memory_min: 50000
    gpu_memory_utilization: 0.9
    gpu_type: NVIDIA-H100-80GB-HBM3
    long_prefill_token_threshold: 2048
    max_model_len: 8192
    max_num_batched_tokens: 2048
    max_num_seqs: 1
    seed: 42
- chunk_size: 4096
  data:
    workloads:
    - deltas:
      - 2609
      - 1179
      - 4355
    - deltas:
      - 5828
      - 553
      - 1150
  name: benchmark-5
  vllm:
    block_size: 16
    gpu_memory_min: 50000
    gpu_memory_utilization: 0.9
    gpu_type: NVIDIA-H100-80GB-HBM3
    long_prefill_token_threshold: 4096
    max_model_len: 8192
    max_num_batched_tokens: 2048
    max_num_seqs: 1
    seed: 42
name: simulator_testing_for_scenario_3
warmstart:
  prompt_count: 50
  prompt_len: 128
