apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blis-pvc
  namespace: blis
spec:
  storageClassName: "ibm-spectrum-scale-fileset"
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi